# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_poppy_client', [dirname(__file__)])
        except ImportError:
            import _poppy_client
            return _poppy_client
        if fp is not None:
            try:
                _mod = imp.load_module('_poppy_client', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _poppy_client = swig_import_helper()
    del swig_import_helper
else:
    import _poppy_client
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class RpcControllerSwig(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RpcControllerSwig, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RpcControllerSwig, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _poppy_client.new_RpcControllerSwig()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _poppy_client.delete_RpcControllerSwig
    __del__ = lambda self : None;
    def Reset(self): return _poppy_client.RpcControllerSwig_Reset(self)
    def Failed(self): return _poppy_client.RpcControllerSwig_Failed(self)
    def ErrorText(self): return _poppy_client.RpcControllerSwig_ErrorText(self)
    def ErrorCode(self): return _poppy_client.RpcControllerSwig_ErrorCode(self)
    def RemoteAddressString(self): return _poppy_client.RpcControllerSwig_RemoteAddressString(self)
    def SetTimeout(self, *args): return _poppy_client.RpcControllerSwig_SetTimeout(self, *args)
    def SetRequestCompressType(self, *args): return _poppy_client.RpcControllerSwig_SetRequestCompressType(self, *args)
    def SetResponseCompressType(self, *args): return _poppy_client.RpcControllerSwig_SetResponseCompressType(self, *args)
    def Timeout(self): return _poppy_client.RpcControllerSwig_Timeout(self)
    def set_method_full_name(self, *args): return _poppy_client.RpcControllerSwig_set_method_full_name(self, *args)
    def SetFailed(self, *args): return _poppy_client.RpcControllerSwig_SetFailed(self, *args)
RpcControllerSwig_swigregister = _poppy_client.RpcControllerSwig_swigregister
RpcControllerSwig_swigregister(RpcControllerSwig)

class RpcClient(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RpcClient, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RpcClient, name)
    __repr__ = _swig_repr
    def __init__(self, num_threads=0): 
        this = _poppy_client.new_RpcClient(num_threads)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _poppy_client.delete_RpcClient
    __del__ = lambda self : None;
RpcClient_swigregister = _poppy_client.RpcClient_swigregister
RpcClient_swigregister(RpcClient)

class ResponseHandler(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ResponseHandler, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ResponseHandler, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _poppy_client.delete_ResponseHandler
    __del__ = lambda self : None;
    def Run(self, *args): return _poppy_client.ResponseHandler_Run(self, *args)
    def __init__(self): 
        if self.__class__ == ResponseHandler:
            _self = None
        else:
            _self = self
        this = _poppy_client.new_ResponseHandler(_self, )
        try: self.this.append(this)
        except: self.this = this
    def __disown__(self):
        self.this.disown()
        _poppy_client.disown_ResponseHandler(self)
        return weakref_proxy(self)
ResponseHandler_swigregister = _poppy_client.ResponseHandler_swigregister
ResponseHandler_swigregister(ResponseHandler)

class RpcChannelSwig(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RpcChannelSwig, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RpcChannelSwig, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _poppy_client.new_RpcChannelSwig(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _poppy_client.delete_RpcChannelSwig
    __del__ = lambda self : None;
    def RawCallMethod(self, *args): return _poppy_client.RpcChannelSwig_RawCallMethod(self, *args)
RpcChannelSwig_swigregister = _poppy_client.RpcChannelSwig_swigregister
RpcChannelSwig_swigregister(RpcChannelSwig)

# This file is compatible with both classic and new-style classes.


