# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='poppy/rpc_error_code_info.proto',
  package='poppy',
  serialized_pb='\n\x1fpoppy/rpc_error_code_info.proto\x12\x05poppy*\xe1\x05\n\x0cRpcErrorCode\x12\x0f\n\x0bRPC_SUCCESS\x10\x00\x12#\n\x1fRPC_ERROR_PARSE_REQUEST_MESSAGE\x10\x01\x12$\n RPC_ERROR_PARSE_RESPONSE_MESSAGE\x10\x02\x12$\n RPC_ERROR_PARSE_RESPONES_MESSAGE\x10\x02\x12 \n\x1cRPC_ERROR_UNCOMPRESS_MESSAGE\x10\x03\x12\x1b\n\x17RPC_ERROR_COMPRESS_TYPE\x10\x04\x12%\n!RPC_ERROR_NOT_SPECIFY_METHOD_NAME\x10\x05\x12\x19\n\x15RPC_ERROR_METHOD_NAME\x10\x06\x12\x1b\n\x17RPC_ERROR_FOUND_SERVICE\x10\x07\x12\x1a\n\x16RPC_ERROR_FOUND_METHOD\x10\x08\x12\x1e\n\x1aRPC_ERROR_CHANNEL_SHUTDOWN\x10\t\x12#\n\x1fRPC_ERROR_ALL_REQUEST_DISCARDED\x10\t\x12\x1f\n\x1bRPC_ERROR_CONNECTION_CLOSED\x10\n\x12\x1d\n\x19RPC_ERROR_REQUEST_TIMEOUT\x10\x0b\x12 \n\x1cRPC_ERROR_SERVER_UNAVAILABLE\x10\x0c\x12!\n\x1dRPC_ERROR_SERVICE_UNREACHABLE\x10\r\x12 \n\x1cRPC_ERROR_SERVER_UNREACHABLE\x10\r\x12\x15\n\x11RPC_ERROR_NO_AUTH\x10\x0e\x12\x1d\n\x19RPC_ERROR_SERVER_SHUTDOWN\x10\x0f\x12\x1e\n\x1aRPC_ERROR_SEND_BUFFER_FULL\x10\x10\x12!\n\x1dRPC_ERROR_NETWORK_UNREACHABLE\x10\x11\x12\x16\n\x11RPC_ERROR_UNKNOWN\x10\xe7\x07\x12\x18\n\x13RPC_ERROR_FROM_USER\x10\xe8\x07\x42\x10\n\x0e\x63om.soso.poppy')

_RPCERRORCODE = descriptor.EnumDescriptor(
  name='RpcErrorCode',
  full_name='poppy.RpcErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RPC_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_PARSE_REQUEST_MESSAGE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_PARSE_RESPONSE_MESSAGE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_PARSE_RESPONES_MESSAGE', index=3, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_UNCOMPRESS_MESSAGE', index=4, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_COMPRESS_TYPE', index=5, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_NOT_SPECIFY_METHOD_NAME', index=6, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_METHOD_NAME', index=7, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_FOUND_SERVICE', index=8, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_FOUND_METHOD', index=9, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_CHANNEL_SHUTDOWN', index=10, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_ALL_REQUEST_DISCARDED', index=11, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_CONNECTION_CLOSED', index=12, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_REQUEST_TIMEOUT', index=13, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_SERVER_UNAVAILABLE', index=14, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_SERVICE_UNREACHABLE', index=15, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_SERVER_UNREACHABLE', index=16, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_NO_AUTH', index=17, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_SERVER_SHUTDOWN', index=18, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_SEND_BUFFER_FULL', index=19, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_NETWORK_UNREACHABLE', index=20, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_UNKNOWN', index=21, number=999,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RPC_ERROR_FROM_USER', index=22, number=1000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=43,
  serialized_end=780,
)


RPC_SUCCESS = 0
RPC_ERROR_PARSE_REQUEST_MESSAGE = 1
RPC_ERROR_PARSE_RESPONSE_MESSAGE = 2
RPC_ERROR_PARSE_RESPONES_MESSAGE = 2
RPC_ERROR_UNCOMPRESS_MESSAGE = 3
RPC_ERROR_COMPRESS_TYPE = 4
RPC_ERROR_NOT_SPECIFY_METHOD_NAME = 5
RPC_ERROR_METHOD_NAME = 6
RPC_ERROR_FOUND_SERVICE = 7
RPC_ERROR_FOUND_METHOD = 8
RPC_ERROR_CHANNEL_SHUTDOWN = 9
RPC_ERROR_ALL_REQUEST_DISCARDED = 9
RPC_ERROR_CONNECTION_CLOSED = 10
RPC_ERROR_REQUEST_TIMEOUT = 11
RPC_ERROR_SERVER_UNAVAILABLE = 12
RPC_ERROR_SERVICE_UNREACHABLE = 13
RPC_ERROR_SERVER_UNREACHABLE = 13
RPC_ERROR_NO_AUTH = 14
RPC_ERROR_SERVER_SHUTDOWN = 15
RPC_ERROR_SEND_BUFFER_FULL = 16
RPC_ERROR_NETWORK_UNREACHABLE = 17
RPC_ERROR_UNKNOWN = 999
RPC_ERROR_FROM_USER = 1000




# @@protoc_insertion_point(module_scope)
