# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='poppy/rpc_message.proto',
  package='poppy',
  serialized_pb='\n\x17poppy/rpc_message.proto\x12\x05poppy\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponseB\x10\n\x0e\x63om.soso.poppy')




_EMPTYREQUEST = descriptor.Descriptor(
  name='EmptyRequest',
  full_name='poppy.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=48,
)


_EMPTYRESPONSE = descriptor.Descriptor(
  name='EmptyResponse',
  full_name='poppy.EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=65,
)



class EmptyRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPTYREQUEST
  
  # @@protoc_insertion_point(class_scope:poppy.EmptyRequest)

class EmptyResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPTYRESPONSE
  
  # @@protoc_insertion_point(class_scope:poppy.EmptyResponse)

# @@protoc_insertion_point(module_scope)
